disabled_rules:
  - todo
excluded:
  - pocket.gg/API.swift
  - pocket.gg/Utilities/Constants.swift

cyclomatic_complexity:
  ignores_case_statements: true
identifier_name:
  min_length: 1
line_length:
  warning: 150
  ignores_comments: true
  ignores_function_declarations: true
trailing_whitespace:
  ignores_empty_lines: true
