//
//  VideoGames.swift
//  pocket.gg
//
//  Created by Gabriel Siu on 2020-02-02.
//  Copyright © 2020 Gabriel Siu. All rights reserved.
//
//  List adapted from https://docs.google.com/spreadsheets/d/1Iq-gueeLYeoVbf1oxVzh5942rX9RG8E6Wxn-yhSbvbQ
//

import Foundation

let videoGames = [
    VideoGame(id: 1, name: "Super Smash Bros. Melee"),
    VideoGame(id: 2, name: "Project M"),
    VideoGame(id: 3, name: "Super Smash Bros. for Wii U"),
    VideoGame(id: 4, name: "Super Smash Bros."),
    VideoGame(id: 5, name: "Super Smash Bros. Brawl"),
    VideoGame(id: 6, name: "Other"),
    VideoGame(id: 7, name: "Street Fighter V: Arcade Edition"),
    VideoGame(id: 8, name: "Pokkén Tournament"),
    VideoGame(id: 10, name: "League of Legends"),
    VideoGame(id: 11, name: "Dota 2"),
    VideoGame(id: 12, name: "Counter Strike: Global Offensive"),
    VideoGame(id: 13, name: "Hearthstone"),
    VideoGame(id: 14, name: "Rocket League"),
    VideoGame(id: 15, name: "Brawlhalla"),
    VideoGame(id: 16, name: "Ultra Street Fighter IV"),
    VideoGame(id: 17, name: "TEKKEN 7"),
    VideoGame(id: 18, name: "Ultimate Marvel vs Capcom 3"),
    VideoGame(id: 19, name: "Killer Instinct"),
    VideoGame(id: 20, name: "Splatoon"),
    VideoGame(id: 21, name: "Guilty Gear Xrd"),
    VideoGame(id: 22, name: "Mortal Kombat X"),
    VideoGame(id: 23, name: "Mortal Kombat XL"),
    VideoGame(id: 24, name: "Rivals of Aether"),
    VideoGame(id: 25, name: "Clash Royale"),
    VideoGame(id: 26, name: "Battlerite"),
    VideoGame(id: 28, name: "Rock Paper Scissors"),
    VideoGame(id: 29, name: "Super Smash Bros. for 3DS"),
    VideoGame(id: 30, name: "StarCraft II: Legacy of the Void"),
    VideoGame(id: 31, name: "Overwatch"),
    VideoGame(id: 32, name: "Skullgirls: 2nd Encore"),
    VideoGame(id: 33, name: "Windjammers"),
    VideoGame(id: 34, name: "Disc Jam"),
    VideoGame(id: 35, name: "Injustice 2"),
    VideoGame(id: 36, name: "Guilty Gear Xrd REV2"),
    VideoGame(id: 37, name: "BlazBlue: Central Fiction"),
    VideoGame(id: 38, name: "The King of Fighters XIV"),
    VideoGame(id: 39, name: "Capcom vs. SNK 2"),
    VideoGame(id: 40, name: "For Honor"),
    VideoGame(id: 41, name: "Madden NFL 2017"),
    VideoGame(id: 42, name: "Puyo Puyo VS2"),
    VideoGame(id: 43, name: "StarCraft: Brood War"),
    VideoGame(id: 45, name: "Gears of War 4"),
    VideoGame(id: 88, name: "Brawlout"),
    VideoGame(id: 120, name: "Pokemon Showdown"),
    VideoGame(id: 143, name: "Pokemon Sun & Moon"),
    VideoGame(id: 193, name: "ARMS"),
    VideoGame(id: 287, name: "DRAGON BALL FighterZ"),
    VideoGame(id: 288, name: "Marvel vs. Capcom: Infinite"),
    VideoGame(id: 294, name: "Deformers"),
    VideoGame(id: 327, name: "Splatoon 2"),
    VideoGame(id: 342, name: "Pokemon TCG Online"),
    VideoGame(id: 343, name: "Pokemon TCG"),
    VideoGame(id: 444, name: "SOULCALIBUR V"),
    VideoGame(id: 447, name: "Pokkén Tournament DX"),
    VideoGame(id: 451, name: "Under Night In-Birth Exe: Late[st]"),
    VideoGame(id: 549, name: "Lawbreakers"),
    VideoGame(id: 556, name: "Gwent"),
    VideoGame(id: 562, name: "Madden NFL 2018"),
    VideoGame(id: 582, name: "Vampire Savior"),
    VideoGame(id: 608, name: "Fight of Gods"),
    VideoGame(id: 610, name: "Street Fighter III: 3rd Strike"),
    VideoGame(id: 611, name: "Super Street Fighter II Turbo"),
    VideoGame(id: 614, name: "Street Fighter IV: Champion Edition"),
    VideoGame(id: 705, name: "Tooth and Tail"),
    VideoGame(id: 718, name: "PlayerUnknown's Battlegrounds"),
    VideoGame(id: 752, name: "Quake Champions"),
    VideoGame(id: 791, name: "Paladins: Champions of the Realm"),
    VideoGame(id: 856, name: "Mortal Kombat 9"),
    VideoGame(id: 865, name: "Halo 5: Guardians"),
    VideoGame(id: 904, name: "SOULCALIBUR VI"),
    VideoGame(id: 936, name: "Yu-Gi-Oh! Duel Links"),
    VideoGame(id: 1013, name: "FIFA 18"),
    VideoGame(id: 1015, name: "NBA 2K18"),
    VideoGame(id: 1095, name: "Fortnite"),
    VideoGame(id: 1106, name: "MLB The Show 18"),
    VideoGame(id: 1107, name: "NBA Live 18"),
    VideoGame(id: 1108, name: "UFC 3"),
    VideoGame(id: 1109, name: "NHL 18"),
    VideoGame(id: 1110, name: "WWE 2K18"),
    VideoGame(id: 1144, name: "BlazBlue: Cross Tag Battle"),
    VideoGame(id: 1150, name: "Them's Fightin' Herds"),
    VideoGame(id: 1277, name: "Age of Empires: Definitive Edition"),
    VideoGame(id: 1296, name: "Battalion 1944"),
    VideoGame(id: 1297, name: "Echo Arena"),
    VideoGame(id: 1335, name: "Lethal League"),
    VideoGame(id: 1344, name: "Space Pirate Trainer"),
    VideoGame(id: 1366, name: "Raw Data"),
    VideoGame(id: 1386, name: "Super Smash Bros. Ultimate"),
    VideoGame(id: 1408, name: "Dissidia Final Fantasy NT"),
    VideoGame(id: 1409, name: "Ultra Street Fighter II: The Final Challengers"),
    VideoGame(id: 1465, name: "Chess"),
    VideoGame(id: 1561, name: "Gundam Versus"),
    VideoGame(id: 1756, name: "Tom Clancy's Rainbow Six Siege"),
    VideoGame(id: 1800, name: "Forza Motorsport 7"),
    VideoGame(id: 1837, name: "Midair"),
    VideoGame(id: 1862, name: "Magic the Gathering"),
    VideoGame(id: 1863, name: "Pokemon VGC"),
    VideoGame(id: 1864, name: "Dragon Ball Super Card Game"),
    VideoGame(id: 1930, name: "Street Fighter 30th Anniversary Collection"),
    VideoGame(id: 1937, name: "Blade Strangers"),
    VideoGame(id: 1938, name: "SNK Heroines: Tag Team Frenzy"),
    VideoGame(id: 1969, name: "Slap City"),
    VideoGame(id: 2054, name: "Mario Tennis Aces"),
    VideoGame(id: 2079, name: "Icons: Combat Arena"),
    VideoGame(id: 2091, name: "EXCEED: Fighting System"),
    VideoGame(id: 2094, name: "Roof Rage"),
    VideoGame(id: 2147, name: "Ring Of Elysium"),
    VideoGame(id: 2165, name: "Mario Kart 8 Deluxe"),
    VideoGame(id: 2208, name: "Vainglory"),
    VideoGame(id: 2261, name: "Universal Fighting System"),
    VideoGame(id: 2336, name: "Sailor Moon S"),
    VideoGame(id: 2366, name: "Fighting EX Layer"),
    VideoGame(id: 2405, name: "Overcooked"),
    VideoGame(id: 2407, name: "Smite"),
    VideoGame(id: 2409, name: "Realm Royale"),
    VideoGame(id: 2480, name: "Madden NFL 2019"),
    VideoGame(id: 2524, name: "DimensionsVS"),
    VideoGame(id: 2555, name: "Halo 3: Master Chief Collection"),
    VideoGame(id: 2563, name: "NBA 2K19"),
    VideoGame(id: 2572, name: "Ironsight"),
    VideoGame(id: 2650, name: "Team Fortress 2"),
    VideoGame(id: 2659, name: "FIFA 19"),
    VideoGame(id: 2679, name: "Heroes of the Storm"),
    VideoGame(id: 2719, name: "Splitgate: Arena Warfare"),
    VideoGame(id: 2756, name: "Indie Pogo"),
    VideoGame(id: 2765, name: "Super Mario Party"),
    VideoGame(id: 2774, name: "Call of Duty: Black Ops 4"),
    VideoGame(id: 2837, name: "Dragon Ball Legends"),
    VideoGame(id: 2842, name: "Killer Queen"),
    VideoGame(id: 2868, name: "Lethal League Blaze"),
    VideoGame(id: 2869, name: "Catherine"),
    VideoGame(id: 2902, name: "Dance Dance Revolution A"),
    VideoGame(id: 2903, name: "Beatmania IIDX 25 Cannon Ballers"),
    VideoGame(id: 2904, name: "Beatmania IIDX 26 Rootage"),
    VideoGame(id: 2905, name: "Sound Voltex IV"),
    VideoGame(id: 2906, name: "Pump it Up Prime 2"),
    VideoGame(id: 2907, name: "Dance Dance Revolution Extreme Pro"),
    VideoGame(id: 2908, name: "In The Groove 2"),
    VideoGame(id: 2909, name: "Jubeat festo"),
    VideoGame(id: 2910, name: "Pop'n music peace"),
    VideoGame(id: 2915, name: "Battlefield V"),
    VideoGame(id: 2930, name: "Dance Rush Stardom"),
    VideoGame(id: 2948, name: "Echo Combat"),
    VideoGame(id: 2979, name: "NHL 19")
]
